# Generated by Django 4.0.1 on 2022-01-24 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.BigIntegerField()),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='gig_thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnbckers.gig', unique=True)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnbckers.user', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='gig',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnbckers.user', unique=True),
        ),
    ]
